apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ebstest-pvc
    annotations:
      volume.beta.kubernetes.io/storage-class: gp2
  spec:
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Delete
    resources:
      requests:
        storage: 15Gi
